%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\thoma\Desktop\Turbulence project\10.6.21 CTD data\FS20210001_Eddy0621_stn1_conv.cnv
%
% To extend the code to different selected data or a different text file, generate a function instead of a script.

% Auto-generated by MATLAB on 2021/07/29 12:54:49

%% Initialize variables.
filename = 'C:\Users\thoma\Desktop\Turbulence project\10.6.21 CTD data\10_6_10.cnv';

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column9: double (%f)
%   column10: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%11f%11f%11f%11f%11f%*11*s%*11*s%*11f%11f%11f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this code. If an error occurs for a different file, try regenerating the code from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', 'EmptyValue', NaN,  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post processing code is included. To generate code which works for unimportable data, select unimportable cells in a file and regenerate the script.

%% Allocate imported array to column variable names
depth_10_6_10 = dataArray{:, 1};
press_10_6_10 = dataArray{:, 2};
temp_10_6_10 = dataArray{:, 3};
sal_10_6_10 = dataArray{:, 4};
dens_10_6_10 = dataArray{:, 5};
ox_mgl_10_6_10 = dataArray{:, 6};
ox_percent_10_6_10 = dataArray{:, 7};


%% Clear temporary variables
clearvars filename formatSpec fileID dataArray ans;


% Convert salinity and temperature
abs_sal_10_6_10 = gsw_SA_from_SP(sal_10_6_10, press_10_6_10, long(10), lat(10));
cons_temp_10_6_10 = gsw_CT_from_t(abs_sal_10_6_10, temp_10_6_10, press_10_6_10);